package dev.youtiao.movie_booking.dao.entities;

public class CommentUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_user.comment_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_user.user_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_user.movie_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer movieId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_user.has_rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Byte hasRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_user.rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment_user.content
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_user.comment_id
     *
     * @return the value of comment_user.comment_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_user.comment_id
     *
     * @param commentId the value for comment_user.comment_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_user.user_id
     *
     * @return the value of comment_user.user_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_user.user_id
     *
     * @param userId the value for comment_user.user_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_user.movie_id
     *
     * @return the value of comment_user.movie_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_user.movie_id
     *
     * @param movieId the value for comment_user.movie_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_user.has_rating
     *
     * @return the value of comment_user.has_rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Byte getHasRating() {
        return hasRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_user.has_rating
     *
     * @param hasRating the value for comment_user.has_rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setHasRating(Byte hasRating) {
        this.hasRating = hasRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_user.rating
     *
     * @return the value of comment_user.rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_user.rating
     *
     * @param rating the value for comment_user.rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment_user.content
     *
     * @return the value of comment_user.content
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment_user.content
     *
     * @param content the value for comment_user.content
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}