package dev.youtiao.movie_booking.dao.entities;

import java.math.BigDecimal;
import java.util.Date;

public class MovieBookingSystemPlay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_play.play_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer playId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_play.start_from
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Date startFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_play.end_at
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Date endAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_play.price
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_play.movie_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer movieId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_play.theatre_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer theatreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_play.seats_occupied
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer seatsOccupied;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_play.seats_total
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer seatsTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_play.hall_no
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer hallNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_play.play_id
     *
     * @return the value of movie_booking_system_play.play_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getPlayId() {
        return playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_play.play_id
     *
     * @param playId the value for movie_booking_system_play.play_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setPlayId(Integer playId) {
        this.playId = playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_play.start_from
     *
     * @return the value of movie_booking_system_play.start_from
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Date getStartFrom() {
        return startFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_play.start_from
     *
     * @param startFrom the value for movie_booking_system_play.start_from
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setStartFrom(Date startFrom) {
        this.startFrom = startFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_play.end_at
     *
     * @return the value of movie_booking_system_play.end_at
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Date getEndAt() {
        return endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_play.end_at
     *
     * @param endAt the value for movie_booking_system_play.end_at
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setEndAt(Date endAt) {
        this.endAt = endAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_play.price
     *
     * @return the value of movie_booking_system_play.price
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_play.price
     *
     * @param price the value for movie_booking_system_play.price
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_play.movie_id
     *
     * @return the value of movie_booking_system_play.movie_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_play.movie_id
     *
     * @param movieId the value for movie_booking_system_play.movie_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_play.theatre_id
     *
     * @return the value of movie_booking_system_play.theatre_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getTheatreId() {
        return theatreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_play.theatre_id
     *
     * @param theatreId the value for movie_booking_system_play.theatre_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setTheatreId(Integer theatreId) {
        this.theatreId = theatreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_play.seats_occupied
     *
     * @return the value of movie_booking_system_play.seats_occupied
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getSeatsOccupied() {
        return seatsOccupied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_play.seats_occupied
     *
     * @param seatsOccupied the value for movie_booking_system_play.seats_occupied
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setSeatsOccupied(Integer seatsOccupied) {
        this.seatsOccupied = seatsOccupied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_play.seats_total
     *
     * @return the value of movie_booking_system_play.seats_total
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getSeatsTotal() {
        return seatsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_play.seats_total
     *
     * @param seatsTotal the value for movie_booking_system_play.seats_total
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setSeatsTotal(Integer seatsTotal) {
        this.seatsTotal = seatsTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_play.hall_no
     *
     * @return the value of movie_booking_system_play.hall_no
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getHallNo() {
        return hallNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_play.hall_no
     *
     * @param hallNo the value for movie_booking_system_play.hall_no
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setHallNo(Integer hallNo) {
        this.hallNo = hallNo;
    }
}