package dev.youtiao.movie_booking.dao.entities;

public class MovieBookingSeats {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_seats.seat_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer seatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_seats.seat_no
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer seatNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_seats.play_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer playId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_seats.seat_id
     *
     * @return the value of movie_booking_seats.seat_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_seats.seat_id
     *
     * @param seatId the value for movie_booking_seats.seat_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_seats.seat_no
     *
     * @return the value of movie_booking_seats.seat_no
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getSeatNo() {
        return seatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_seats.seat_no
     *
     * @param seatNo the value for movie_booking_seats.seat_no
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setSeatNo(Integer seatNo) {
        this.seatNo = seatNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_seats.play_id
     *
     * @return the value of movie_booking_seats.play_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getPlayId() {
        return playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_seats.play_id
     *
     * @param playId the value for movie_booking_seats.play_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setPlayId(Integer playId) {
        this.playId = playId;
    }
}