package dev.youtiao.movie_booking.dao.entities;

public class MovieBookingOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_order.order_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_order.user_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_order.play_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer playId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_order.seat_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer seatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_order.pay_status
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String payStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_order.order_id
     *
     * @return the value of movie_booking_order.order_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_order.order_id
     *
     * @param orderId the value for movie_booking_order.order_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_order.user_id
     *
     * @return the value of movie_booking_order.user_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_order.user_id
     *
     * @param userId the value for movie_booking_order.user_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_order.play_id
     *
     * @return the value of movie_booking_order.play_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getPlayId() {
        return playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_order.play_id
     *
     * @param playId the value for movie_booking_order.play_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setPlayId(Integer playId) {
        this.playId = playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_order.seat_id
     *
     * @return the value of movie_booking_order.seat_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_order.seat_id
     *
     * @param seatId the value for movie_booking_order.seat_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_order.pay_status
     *
     * @return the value of movie_booking_order.pay_status
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_order.pay_status
     *
     * @param payStatus the value for movie_booking_order.pay_status
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }
}