package dev.youtiao.movie_booking.dao.entities;

public class MovieBookingSystemMovies {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_movies.movie_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer movieId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_movies.name
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_movies.length
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_movies.cover_img_url
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String coverImgUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_movies.director
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String director;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_movies.cast
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String cast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_movies.genre
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String genre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_movies.introduction
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_movies.movie_id
     *
     * @return the value of movie_booking_system_movies.movie_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_movies.movie_id
     *
     * @param movieId the value for movie_booking_system_movies.movie_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_movies.name
     *
     * @return the value of movie_booking_system_movies.name
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_movies.name
     *
     * @param name the value for movie_booking_system_movies.name
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_movies.length
     *
     * @return the value of movie_booking_system_movies.length
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getLength() {
        return length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_movies.length
     *
     * @param length the value for movie_booking_system_movies.length
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setLength(Integer length) {
        this.length = length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_movies.cover_img_url
     *
     * @return the value of movie_booking_system_movies.cover_img_url
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getCoverImgUrl() {
        return coverImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_movies.cover_img_url
     *
     * @param coverImgUrl the value for movie_booking_system_movies.cover_img_url
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setCoverImgUrl(String coverImgUrl) {
        this.coverImgUrl = coverImgUrl == null ? null : coverImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_movies.director
     *
     * @return the value of movie_booking_system_movies.director
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_movies.director
     *
     * @param director the value for movie_booking_system_movies.director
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setDirector(String director) {
        this.director = director == null ? null : director.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_movies.cast
     *
     * @return the value of movie_booking_system_movies.cast
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getCast() {
        return cast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_movies.cast
     *
     * @param cast the value for movie_booking_system_movies.cast
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setCast(String cast) {
        this.cast = cast == null ? null : cast.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_movies.genre
     *
     * @return the value of movie_booking_system_movies.genre
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getGenre() {
        return genre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_movies.genre
     *
     * @param genre the value for movie_booking_system_movies.genre
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setGenre(String genre) {
        this.genre = genre == null ? null : genre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_movies.introduction
     *
     * @return the value of movie_booking_system_movies.introduction
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_movies.introduction
     *
     * @param introduction the value for movie_booking_system_movies.introduction
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}