package dev.youtiao.movie_booking.dao.entities;

import java.util.Date;

public class MovieBookingOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_order.order_id
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_order.user_id
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_order.play_id
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    private Integer playId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_order.seat_id
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    private Integer seatId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_order.pay_status
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    private String payStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_order.create_time
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_order.update_time
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_order.order_id
     *
     * @return the value of movie_booking_order.order_id
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_order.order_id
     *
     * @param orderId the value for movie_booking_order.order_id
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_order.user_id
     *
     * @return the value of movie_booking_order.user_id
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_order.user_id
     *
     * @param userId the value for movie_booking_order.user_id
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_order.play_id
     *
     * @return the value of movie_booking_order.play_id
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public Integer getPlayId() {
        return playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_order.play_id
     *
     * @param playId the value for movie_booking_order.play_id
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public void setPlayId(Integer playId) {
        this.playId = playId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_order.seat_id
     *
     * @return the value of movie_booking_order.seat_id
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public Integer getSeatId() {
        return seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_order.seat_id
     *
     * @param seatId the value for movie_booking_order.seat_id
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public void setSeatId(Integer seatId) {
        this.seatId = seatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_order.pay_status
     *
     * @return the value of movie_booking_order.pay_status
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public String getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_order.pay_status
     *
     * @param payStatus the value for movie_booking_order.pay_status
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public void setPayStatus(String payStatus) {
        this.payStatus = payStatus == null ? null : payStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_order.create_time
     *
     * @return the value of movie_booking_order.create_time
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_order.create_time
     *
     * @param createTime the value for movie_booking_order.create_time
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_order.update_time
     *
     * @return the value of movie_booking_order.update_time
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_order.update_time
     *
     * @param updateTime the value for movie_booking_order.update_time
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}