package dev.youtiao.movie_booking.dao.entities;

public class MovieBookingSystemUsers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_users.user_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_users.name
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_users.hashed_passwd
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String hashedPasswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_users.display_name
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column movie_booking_system_users.role
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_users.user_id
     *
     * @return the value of movie_booking_system_users.user_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_users.user_id
     *
     * @param userId the value for movie_booking_system_users.user_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_users.name
     *
     * @return the value of movie_booking_system_users.name
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_users.name
     *
     * @param name the value for movie_booking_system_users.name
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_users.hashed_passwd
     *
     * @return the value of movie_booking_system_users.hashed_passwd
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getHashedPasswd() {
        return hashedPasswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_users.hashed_passwd
     *
     * @param hashedPasswd the value for movie_booking_system_users.hashed_passwd
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setHashedPasswd(String hashedPasswd) {
        this.hashedPasswd = hashedPasswd == null ? null : hashedPasswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_users.display_name
     *
     * @return the value of movie_booking_system_users.display_name
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_users.display_name
     *
     * @param displayName the value for movie_booking_system_users.display_name
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column movie_booking_system_users.role
     *
     * @return the value of movie_booking_system_users.role
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column movie_booking_system_users.role
     *
     * @param role the value for movie_booking_system_users.role
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }
}