package dev.youtiao.movie_booking.dao.entities;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class RatingMovieExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public RatingMovieExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMovieIdIsNull() {
            addCriterion("movie_id is null");
            return (Criteria) this;
        }

        public Criteria andMovieIdIsNotNull() {
            addCriterion("movie_id is not null");
            return (Criteria) this;
        }

        public Criteria andMovieIdEqualTo(Integer value) {
            addCriterion("movie_id =", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdNotEqualTo(Integer value) {
            addCriterion("movie_id <>", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdGreaterThan(Integer value) {
            addCriterion("movie_id >", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("movie_id >=", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdLessThan(Integer value) {
            addCriterion("movie_id <", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdLessThanOrEqualTo(Integer value) {
            addCriterion("movie_id <=", value, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdIn(List<Integer> values) {
            addCriterion("movie_id in", values, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdNotIn(List<Integer> values) {
            addCriterion("movie_id not in", values, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdBetween(Integer value1, Integer value2) {
            addCriterion("movie_id between", value1, value2, "movieId");
            return (Criteria) this;
        }

        public Criteria andMovieIdNotBetween(Integer value1, Integer value2) {
            addCriterion("movie_id not between", value1, value2, "movieId");
            return (Criteria) this;
        }

        public Criteria andTotalAuditRatingIsNull() {
            addCriterion("total_audit_rating is null");
            return (Criteria) this;
        }

        public Criteria andTotalAuditRatingIsNotNull() {
            addCriterion("total_audit_rating is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAuditRatingEqualTo(Long value) {
            addCriterion("total_audit_rating =", value, "totalAuditRating");
            return (Criteria) this;
        }

        public Criteria andTotalAuditRatingNotEqualTo(Long value) {
            addCriterion("total_audit_rating <>", value, "totalAuditRating");
            return (Criteria) this;
        }

        public Criteria andTotalAuditRatingGreaterThan(Long value) {
            addCriterion("total_audit_rating >", value, "totalAuditRating");
            return (Criteria) this;
        }

        public Criteria andTotalAuditRatingGreaterThanOrEqualTo(Long value) {
            addCriterion("total_audit_rating >=", value, "totalAuditRating");
            return (Criteria) this;
        }

        public Criteria andTotalAuditRatingLessThan(Long value) {
            addCriterion("total_audit_rating <", value, "totalAuditRating");
            return (Criteria) this;
        }

        public Criteria andTotalAuditRatingLessThanOrEqualTo(Long value) {
            addCriterion("total_audit_rating <=", value, "totalAuditRating");
            return (Criteria) this;
        }

        public Criteria andTotalAuditRatingIn(List<Long> values) {
            addCriterion("total_audit_rating in", values, "totalAuditRating");
            return (Criteria) this;
        }

        public Criteria andTotalAuditRatingNotIn(List<Long> values) {
            addCriterion("total_audit_rating not in", values, "totalAuditRating");
            return (Criteria) this;
        }

        public Criteria andTotalAuditRatingBetween(Long value1, Long value2) {
            addCriterion("total_audit_rating between", value1, value2, "totalAuditRating");
            return (Criteria) this;
        }

        public Criteria andTotalAuditRatingNotBetween(Long value1, Long value2) {
            addCriterion("total_audit_rating not between", value1, value2, "totalAuditRating");
            return (Criteria) this;
        }

        public Criteria andAuditRatingCountIsNull() {
            addCriterion("audit_rating_count is null");
            return (Criteria) this;
        }

        public Criteria andAuditRatingCountIsNotNull() {
            addCriterion("audit_rating_count is not null");
            return (Criteria) this;
        }

        public Criteria andAuditRatingCountEqualTo(Integer value) {
            addCriterion("audit_rating_count =", value, "auditRatingCount");
            return (Criteria) this;
        }

        public Criteria andAuditRatingCountNotEqualTo(Integer value) {
            addCriterion("audit_rating_count <>", value, "auditRatingCount");
            return (Criteria) this;
        }

        public Criteria andAuditRatingCountGreaterThan(Integer value) {
            addCriterion("audit_rating_count >", value, "auditRatingCount");
            return (Criteria) this;
        }

        public Criteria andAuditRatingCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("audit_rating_count >=", value, "auditRatingCount");
            return (Criteria) this;
        }

        public Criteria andAuditRatingCountLessThan(Integer value) {
            addCriterion("audit_rating_count <", value, "auditRatingCount");
            return (Criteria) this;
        }

        public Criteria andAuditRatingCountLessThanOrEqualTo(Integer value) {
            addCriterion("audit_rating_count <=", value, "auditRatingCount");
            return (Criteria) this;
        }

        public Criteria andAuditRatingCountIn(List<Integer> values) {
            addCriterion("audit_rating_count in", values, "auditRatingCount");
            return (Criteria) this;
        }

        public Criteria andAuditRatingCountNotIn(List<Integer> values) {
            addCriterion("audit_rating_count not in", values, "auditRatingCount");
            return (Criteria) this;
        }

        public Criteria andAuditRatingCountBetween(Integer value1, Integer value2) {
            addCriterion("audit_rating_count between", value1, value2, "auditRatingCount");
            return (Criteria) this;
        }

        public Criteria andAuditRatingCountNotBetween(Integer value1, Integer value2) {
            addCriterion("audit_rating_count not between", value1, value2, "auditRatingCount");
            return (Criteria) this;
        }

        public Criteria andFinalAuditRatingIsNull() {
            addCriterion("final_audit_rating is null");
            return (Criteria) this;
        }

        public Criteria andFinalAuditRatingIsNotNull() {
            addCriterion("final_audit_rating is not null");
            return (Criteria) this;
        }

        public Criteria andFinalAuditRatingEqualTo(BigDecimal value) {
            addCriterion("final_audit_rating =", value, "finalAuditRating");
            return (Criteria) this;
        }

        public Criteria andFinalAuditRatingNotEqualTo(BigDecimal value) {
            addCriterion("final_audit_rating <>", value, "finalAuditRating");
            return (Criteria) this;
        }

        public Criteria andFinalAuditRatingGreaterThan(BigDecimal value) {
            addCriterion("final_audit_rating >", value, "finalAuditRating");
            return (Criteria) this;
        }

        public Criteria andFinalAuditRatingGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("final_audit_rating >=", value, "finalAuditRating");
            return (Criteria) this;
        }

        public Criteria andFinalAuditRatingLessThan(BigDecimal value) {
            addCriterion("final_audit_rating <", value, "finalAuditRating");
            return (Criteria) this;
        }

        public Criteria andFinalAuditRatingLessThanOrEqualTo(BigDecimal value) {
            addCriterion("final_audit_rating <=", value, "finalAuditRating");
            return (Criteria) this;
        }

        public Criteria andFinalAuditRatingIn(List<BigDecimal> values) {
            addCriterion("final_audit_rating in", values, "finalAuditRating");
            return (Criteria) this;
        }

        public Criteria andFinalAuditRatingNotIn(List<BigDecimal> values) {
            addCriterion("final_audit_rating not in", values, "finalAuditRating");
            return (Criteria) this;
        }

        public Criteria andFinalAuditRatingBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("final_audit_rating between", value1, value2, "finalAuditRating");
            return (Criteria) this;
        }

        public Criteria andFinalAuditRatingNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("final_audit_rating not between", value1, value2, "finalAuditRating");
            return (Criteria) this;
        }

        public Criteria andImdbRatingIsNull() {
            addCriterion("imdb_rating is null");
            return (Criteria) this;
        }

        public Criteria andImdbRatingIsNotNull() {
            addCriterion("imdb_rating is not null");
            return (Criteria) this;
        }

        public Criteria andImdbRatingEqualTo(BigDecimal value) {
            addCriterion("imdb_rating =", value, "imdbRating");
            return (Criteria) this;
        }

        public Criteria andImdbRatingNotEqualTo(BigDecimal value) {
            addCriterion("imdb_rating <>", value, "imdbRating");
            return (Criteria) this;
        }

        public Criteria andImdbRatingGreaterThan(BigDecimal value) {
            addCriterion("imdb_rating >", value, "imdbRating");
            return (Criteria) this;
        }

        public Criteria andImdbRatingGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("imdb_rating >=", value, "imdbRating");
            return (Criteria) this;
        }

        public Criteria andImdbRatingLessThan(BigDecimal value) {
            addCriterion("imdb_rating <", value, "imdbRating");
            return (Criteria) this;
        }

        public Criteria andImdbRatingLessThanOrEqualTo(BigDecimal value) {
            addCriterion("imdb_rating <=", value, "imdbRating");
            return (Criteria) this;
        }

        public Criteria andImdbRatingIn(List<BigDecimal> values) {
            addCriterion("imdb_rating in", values, "imdbRating");
            return (Criteria) this;
        }

        public Criteria andImdbRatingNotIn(List<BigDecimal> values) {
            addCriterion("imdb_rating not in", values, "imdbRating");
            return (Criteria) this;
        }

        public Criteria andImdbRatingBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("imdb_rating between", value1, value2, "imdbRating");
            return (Criteria) this;
        }

        public Criteria andImdbRatingNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("imdb_rating not between", value1, value2, "imdbRating");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rating_movie
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 05 11:51:48 PDT 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}