package dev.youtiao.movie_booking.dao.entities;

import java.math.BigDecimal;

public class RatingMovie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating_movie.movie_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer movieId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating_movie.total_audit_rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Long totalAuditRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating_movie.audit_rating_count
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer auditRatingCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating_movie.final_audit_rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private BigDecimal finalAuditRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rating_movie.imdb_rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private BigDecimal imdbRating;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating_movie.movie_id
     *
     * @return the value of rating_movie.movie_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating_movie.movie_id
     *
     * @param movieId the value for rating_movie.movie_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating_movie.total_audit_rating
     *
     * @return the value of rating_movie.total_audit_rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Long getTotalAuditRating() {
        return totalAuditRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating_movie.total_audit_rating
     *
     * @param totalAuditRating the value for rating_movie.total_audit_rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setTotalAuditRating(Long totalAuditRating) {
        this.totalAuditRating = totalAuditRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating_movie.audit_rating_count
     *
     * @return the value of rating_movie.audit_rating_count
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getAuditRatingCount() {
        return auditRatingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating_movie.audit_rating_count
     *
     * @param auditRatingCount the value for rating_movie.audit_rating_count
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setAuditRatingCount(Integer auditRatingCount) {
        this.auditRatingCount = auditRatingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating_movie.final_audit_rating
     *
     * @return the value of rating_movie.final_audit_rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public BigDecimal getFinalAuditRating() {
        return finalAuditRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating_movie.final_audit_rating
     *
     * @param finalAuditRating the value for rating_movie.final_audit_rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setFinalAuditRating(BigDecimal finalAuditRating) {
        this.finalAuditRating = finalAuditRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rating_movie.imdb_rating
     *
     * @return the value of rating_movie.imdb_rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public BigDecimal getImdbRating() {
        return imdbRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rating_movie.imdb_rating
     *
     * @param imdbRating the value for rating_movie.imdb_rating
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setImdbRating(BigDecimal imdbRating) {
        this.imdbRating = imdbRating;
    }
}