package dev.youtiao.movie_booking.dao.entities;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TheatreInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public TheatreInfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTheatreIdIsNull() {
            addCriterion("theatre_id is null");
            return (Criteria) this;
        }

        public Criteria andTheatreIdIsNotNull() {
            addCriterion("theatre_id is not null");
            return (Criteria) this;
        }

        public Criteria andTheatreIdEqualTo(Integer value) {
            addCriterion("theatre_id =", value, "theatreId");
            return (Criteria) this;
        }

        public Criteria andTheatreIdNotEqualTo(Integer value) {
            addCriterion("theatre_id <>", value, "theatreId");
            return (Criteria) this;
        }

        public Criteria andTheatreIdGreaterThan(Integer value) {
            addCriterion("theatre_id >", value, "theatreId");
            return (Criteria) this;
        }

        public Criteria andTheatreIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("theatre_id >=", value, "theatreId");
            return (Criteria) this;
        }

        public Criteria andTheatreIdLessThan(Integer value) {
            addCriterion("theatre_id <", value, "theatreId");
            return (Criteria) this;
        }

        public Criteria andTheatreIdLessThanOrEqualTo(Integer value) {
            addCriterion("theatre_id <=", value, "theatreId");
            return (Criteria) this;
        }

        public Criteria andTheatreIdIn(List<Integer> values) {
            addCriterion("theatre_id in", values, "theatreId");
            return (Criteria) this;
        }

        public Criteria andTheatreIdNotIn(List<Integer> values) {
            addCriterion("theatre_id not in", values, "theatreId");
            return (Criteria) this;
        }

        public Criteria andTheatreIdBetween(Integer value1, Integer value2) {
            addCriterion("theatre_id between", value1, value2, "theatreId");
            return (Criteria) this;
        }

        public Criteria andTheatreIdNotBetween(Integer value1, Integer value2) {
            addCriterion("theatre_id not between", value1, value2, "theatreId");
            return (Criteria) this;
        }

        public Criteria andTheatreNameIsNull() {
            addCriterion("theatre_name is null");
            return (Criteria) this;
        }

        public Criteria andTheatreNameIsNotNull() {
            addCriterion("theatre_name is not null");
            return (Criteria) this;
        }

        public Criteria andTheatreNameEqualTo(String value) {
            addCriterion("theatre_name =", value, "theatreName");
            return (Criteria) this;
        }

        public Criteria andTheatreNameNotEqualTo(String value) {
            addCriterion("theatre_name <>", value, "theatreName");
            return (Criteria) this;
        }

        public Criteria andTheatreNameGreaterThan(String value) {
            addCriterion("theatre_name >", value, "theatreName");
            return (Criteria) this;
        }

        public Criteria andTheatreNameGreaterThanOrEqualTo(String value) {
            addCriterion("theatre_name >=", value, "theatreName");
            return (Criteria) this;
        }

        public Criteria andTheatreNameLessThan(String value) {
            addCriterion("theatre_name <", value, "theatreName");
            return (Criteria) this;
        }

        public Criteria andTheatreNameLessThanOrEqualTo(String value) {
            addCriterion("theatre_name <=", value, "theatreName");
            return (Criteria) this;
        }

        public Criteria andTheatreNameLike(String value) {
            addCriterion("theatre_name like", value, "theatreName");
            return (Criteria) this;
        }

        public Criteria andTheatreNameNotLike(String value) {
            addCriterion("theatre_name not like", value, "theatreName");
            return (Criteria) this;
        }

        public Criteria andTheatreNameIn(List<String> values) {
            addCriterion("theatre_name in", values, "theatreName");
            return (Criteria) this;
        }

        public Criteria andTheatreNameNotIn(List<String> values) {
            addCriterion("theatre_name not in", values, "theatreName");
            return (Criteria) this;
        }

        public Criteria andTheatreNameBetween(String value1, String value2) {
            addCriterion("theatre_name between", value1, value2, "theatreName");
            return (Criteria) this;
        }

        public Criteria andTheatreNameNotBetween(String value1, String value2) {
            addCriterion("theatre_name not between", value1, value2, "theatreName");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressIsNull() {
            addCriterion("theatre_address is null");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressIsNotNull() {
            addCriterion("theatre_address is not null");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressEqualTo(String value) {
            addCriterion("theatre_address =", value, "theatreAddress");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressNotEqualTo(String value) {
            addCriterion("theatre_address <>", value, "theatreAddress");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressGreaterThan(String value) {
            addCriterion("theatre_address >", value, "theatreAddress");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressGreaterThanOrEqualTo(String value) {
            addCriterion("theatre_address >=", value, "theatreAddress");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLessThan(String value) {
            addCriterion("theatre_address <", value, "theatreAddress");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLessThanOrEqualTo(String value) {
            addCriterion("theatre_address <=", value, "theatreAddress");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLike(String value) {
            addCriterion("theatre_address like", value, "theatreAddress");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressNotLike(String value) {
            addCriterion("theatre_address not like", value, "theatreAddress");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressIn(List<String> values) {
            addCriterion("theatre_address in", values, "theatreAddress");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressNotIn(List<String> values) {
            addCriterion("theatre_address not in", values, "theatreAddress");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressBetween(String value1, String value2) {
            addCriterion("theatre_address between", value1, value2, "theatreAddress");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressNotBetween(String value1, String value2) {
            addCriterion("theatre_address not between", value1, value2, "theatreAddress");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLatIsNull() {
            addCriterion("theatre_address_lat is null");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLatIsNotNull() {
            addCriterion("theatre_address_lat is not null");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLatEqualTo(BigDecimal value) {
            addCriterion("theatre_address_lat =", value, "theatreAddressLat");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLatNotEqualTo(BigDecimal value) {
            addCriterion("theatre_address_lat <>", value, "theatreAddressLat");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLatGreaterThan(BigDecimal value) {
            addCriterion("theatre_address_lat >", value, "theatreAddressLat");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLatGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("theatre_address_lat >=", value, "theatreAddressLat");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLatLessThan(BigDecimal value) {
            addCriterion("theatre_address_lat <", value, "theatreAddressLat");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLatLessThanOrEqualTo(BigDecimal value) {
            addCriterion("theatre_address_lat <=", value, "theatreAddressLat");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLatIn(List<BigDecimal> values) {
            addCriterion("theatre_address_lat in", values, "theatreAddressLat");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLatNotIn(List<BigDecimal> values) {
            addCriterion("theatre_address_lat not in", values, "theatreAddressLat");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLatBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("theatre_address_lat between", value1, value2, "theatreAddressLat");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLatNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("theatre_address_lat not between", value1, value2, "theatreAddressLat");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLonIsNull() {
            addCriterion("theatre_address_lon is null");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLonIsNotNull() {
            addCriterion("theatre_address_lon is not null");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLonEqualTo(BigDecimal value) {
            addCriterion("theatre_address_lon =", value, "theatreAddressLon");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLonNotEqualTo(BigDecimal value) {
            addCriterion("theatre_address_lon <>", value, "theatreAddressLon");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLonGreaterThan(BigDecimal value) {
            addCriterion("theatre_address_lon >", value, "theatreAddressLon");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLonGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("theatre_address_lon >=", value, "theatreAddressLon");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLonLessThan(BigDecimal value) {
            addCriterion("theatre_address_lon <", value, "theatreAddressLon");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLonLessThanOrEqualTo(BigDecimal value) {
            addCriterion("theatre_address_lon <=", value, "theatreAddressLon");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLonIn(List<BigDecimal> values) {
            addCriterion("theatre_address_lon in", values, "theatreAddressLon");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLonNotIn(List<BigDecimal> values) {
            addCriterion("theatre_address_lon not in", values, "theatreAddressLon");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLonBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("theatre_address_lon between", value1, value2, "theatreAddressLon");
            return (Criteria) this;
        }

        public Criteria andTheatreAddressLonNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("theatre_address_lon not between", value1, value2, "theatreAddressLon");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table theatre_info
     *
     * @mbg.generated do_not_delete_during_merge Tue Aug 05 11:51:48 PDT 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}