package dev.youtiao.movie_booking.dao.entities;

import java.math.BigDecimal;

public class TheatreInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theatre_info.theatre_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private Integer theatreId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theatre_info.theatre_name
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String theatreName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theatre_info.theatre_address
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private String theatreAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theatre_info.theatre_address_lat
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private BigDecimal theatreAddressLat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column theatre_info.theatre_address_lon
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    private BigDecimal theatreAddressLon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theatre_info.theatre_id
     *
     * @return the value of theatre_info.theatre_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public Integer getTheatreId() {
        return theatreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theatre_info.theatre_id
     *
     * @param theatreId the value for theatre_info.theatre_id
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setTheatreId(Integer theatreId) {
        this.theatreId = theatreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theatre_info.theatre_name
     *
     * @return the value of theatre_info.theatre_name
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getTheatreName() {
        return theatreName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theatre_info.theatre_name
     *
     * @param theatreName the value for theatre_info.theatre_name
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setTheatreName(String theatreName) {
        this.theatreName = theatreName == null ? null : theatreName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theatre_info.theatre_address
     *
     * @return the value of theatre_info.theatre_address
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public String getTheatreAddress() {
        return theatreAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theatre_info.theatre_address
     *
     * @param theatreAddress the value for theatre_info.theatre_address
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setTheatreAddress(String theatreAddress) {
        this.theatreAddress = theatreAddress == null ? null : theatreAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theatre_info.theatre_address_lat
     *
     * @return the value of theatre_info.theatre_address_lat
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public BigDecimal getTheatreAddressLat() {
        return theatreAddressLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theatre_info.theatre_address_lat
     *
     * @param theatreAddressLat the value for theatre_info.theatre_address_lat
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setTheatreAddressLat(BigDecimal theatreAddressLat) {
        this.theatreAddressLat = theatreAddressLat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column theatre_info.theatre_address_lon
     *
     * @return the value of theatre_info.theatre_address_lon
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public BigDecimal getTheatreAddressLon() {
        return theatreAddressLon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column theatre_info.theatre_address_lon
     *
     * @param theatreAddressLon the value for theatre_info.theatre_address_lon
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    public void setTheatreAddressLon(BigDecimal theatreAddressLon) {
        this.theatreAddressLon = theatreAddressLon;
    }
}