package dev.youtiao.movie_booking.dao;

import dev.youtiao.movie_booking.dao.entities.CommentUser;
import dev.youtiao.movie_booking.dao.entities.CommentUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommentUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    long countByExample(CommentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByExample(CommentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insert(CommentUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insertSelective(CommentUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    List<CommentUser> selectByExampleWithBLOBs(CommentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    List<CommentUser> selectByExample(CommentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    CommentUser selectByPrimaryKey(Integer commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExampleSelective(@Param("row") CommentUser row, @Param("example") CommentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") CommentUser row, @Param("example") CommentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExample(@Param("row") CommentUser row, @Param("example") CommentUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKeySelective(CommentUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKeyWithBLOBs(CommentUser row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_user
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKey(CommentUser row);
}