package dev.youtiao.movie_booking.dao;

import dev.youtiao.movie_booking.dao.entities.MovieBookingOrder;
import dev.youtiao.movie_booking.dao.entities.MovieBookingOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MovieBookingOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_order
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    long countByExample(MovieBookingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_order
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    int deleteByExample(MovieBookingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_order
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_order
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    int insert(MovieBookingOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_order
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    int insertSelective(MovieBookingOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_order
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    List<MovieBookingOrder> selectByExample(MovieBookingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_order
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    MovieBookingOrder selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_order
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    int updateByExampleSelective(@Param("row") MovieBookingOrder row, @Param("example") MovieBookingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_order
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    int updateByExample(@Param("row") MovieBookingOrder row, @Param("example") MovieBookingOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_order
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    int updateByPrimaryKeySelective(MovieBookingOrder row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_order
     *
     * @mbg.generated Fri Aug 15 17:39:41 PDT 2025
     */
    int updateByPrimaryKey(MovieBookingOrder row);
}