package dev.youtiao.movie_booking.dao;

import dev.youtiao.movie_booking.dao.entities.MovieBookingSystemUsers;
import dev.youtiao.movie_booking.dao.entities.MovieBookingSystemUsersExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MovieBookingSystemUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_users
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    long countByExample(MovieBookingSystemUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_users
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByExample(MovieBookingSystemUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_users
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_users
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insert(MovieBookingSystemUsers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_users
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insertSelective(MovieBookingSystemUsers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_users
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    List<MovieBookingSystemUsers> selectByExample(MovieBookingSystemUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_users
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    MovieBookingSystemUsers selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_users
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExampleSelective(@Param("row") MovieBookingSystemUsers row, @Param("example") MovieBookingSystemUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_users
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExample(@Param("row") MovieBookingSystemUsers row, @Param("example") MovieBookingSystemUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_users
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKeySelective(MovieBookingSystemUsers row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_users
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKey(MovieBookingSystemUsers row);
}