package dev.youtiao.movie_booking.dao;

import dev.youtiao.movie_booking.dao.entities.MovieBookingSystemPlay;
import dev.youtiao.movie_booking.dao.entities.MovieBookingSystemPlayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Update;

public interface MovieBookingSystemPlayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_play
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    long countByExample(MovieBookingSystemPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_play
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByExample(MovieBookingSystemPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_play
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByPrimaryKey(Integer playId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_play
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insert(MovieBookingSystemPlay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_play
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insertSelective(MovieBookingSystemPlay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_play
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    List<MovieBookingSystemPlay> selectByExample(MovieBookingSystemPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_play
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    MovieBookingSystemPlay selectByPrimaryKey(Integer playId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_play
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExampleSelective(@Param("row") MovieBookingSystemPlay row, @Param("example") MovieBookingSystemPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_play
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExample(@Param("row") MovieBookingSystemPlay row, @Param("example") MovieBookingSystemPlayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_play
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKeySelective(MovieBookingSystemPlay row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_play
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKey(MovieBookingSystemPlay row);

    @Update("update movie_booking_system_play set seats_occupied = seats_occupied + 1 where play_id = #{playId}")
    int incrementSeatOccupied(int playId);

    @Update("update movie_booking_system_play set seats_occupied = seats_occupied - 1 where play_id = #{playId}")
    int decrementSeatOccuplied(int playId);
}