package dev.youtiao.movie_booking.dao;

import dev.youtiao.movie_booking.dao.entities.MovieBookingSeats;
import dev.youtiao.movie_booking.dao.entities.MovieBookingSeatsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MovieBookingSeatsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_seats
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    long countByExample(MovieBookingSeatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_seats
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByExample(MovieBookingSeatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_seats
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByPrimaryKey(Integer seatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_seats
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insert(MovieBookingSeats row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_seats
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insertSelective(MovieBookingSeats row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_seats
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    List<MovieBookingSeats> selectByExample(MovieBookingSeatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_seats
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    MovieBookingSeats selectByPrimaryKey(Integer seatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_seats
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExampleSelective(@Param("row") MovieBookingSeats row, @Param("example") MovieBookingSeatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_seats
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExample(@Param("row") MovieBookingSeats row, @Param("example") MovieBookingSeatsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_seats
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKeySelective(MovieBookingSeats row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_seats
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKey(MovieBookingSeats row);
}