package dev.youtiao.movie_booking.dao;

import dev.youtiao.movie_booking.dao.entities.MovieBookingSystemMovies;
import dev.youtiao.movie_booking.dao.entities.MovieBookingSystemMoviesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MovieBookingSystemMoviesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    long countByExample(MovieBookingSystemMoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByExample(MovieBookingSystemMoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByPrimaryKey(Integer movieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insert(MovieBookingSystemMovies row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insertSelective(MovieBookingSystemMovies row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    List<MovieBookingSystemMovies> selectByExampleWithBLOBs(MovieBookingSystemMoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    List<MovieBookingSystemMovies> selectByExample(MovieBookingSystemMoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    MovieBookingSystemMovies selectByPrimaryKey(Integer movieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExampleSelective(@Param("row") MovieBookingSystemMovies row, @Param("example") MovieBookingSystemMoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") MovieBookingSystemMovies row, @Param("example") MovieBookingSystemMoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExample(@Param("row") MovieBookingSystemMovies row, @Param("example") MovieBookingSystemMoviesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKeySelective(MovieBookingSystemMovies row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKeyWithBLOBs(MovieBookingSystemMovies row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table movie_booking_system_movies
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKey(MovieBookingSystemMovies row);
}