package dev.youtiao.movie_booking.dao;

import dev.youtiao.movie_booking.dao.entities.RatingMovie;
import dev.youtiao.movie_booking.dao.entities.RatingMovieExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RatingMovieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    long countByExample(RatingMovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByExample(RatingMovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByPrimaryKey(Integer movieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insert(RatingMovie row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insertSelective(RatingMovie row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    List<RatingMovie> selectByExample(RatingMovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    RatingMovie selectByPrimaryKey(Integer movieId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExampleSelective(@Param("row") RatingMovie row, @Param("example") RatingMovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExample(@Param("row") RatingMovie row, @Param("example") RatingMovieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKeySelective(RatingMovie row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rating_movie
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKey(RatingMovie row);
}