package dev.youtiao.movie_booking.dao;

import dev.youtiao.movie_booking.dao.entities.TheatreInfo;
import dev.youtiao.movie_booking.dao.entities.TheatreInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TheatreInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    long countByExample(TheatreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByExample(TheatreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int deleteByPrimaryKey(Integer theatreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insert(TheatreInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int insertSelective(TheatreInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    List<TheatreInfo> selectByExample(TheatreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    TheatreInfo selectByPrimaryKey(Integer theatreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExampleSelective(@Param("row") TheatreInfo row, @Param("example") TheatreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByExample(@Param("row") TheatreInfo row, @Param("example") TheatreInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKeySelective(TheatreInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table theatre_info
     *
     * @mbg.generated Tue Aug 05 11:51:48 PDT 2025
     */
    int updateByPrimaryKey(TheatreInfo row);
}